In [ ]:
### Carregar as Libraries
import numpy as np
import pandas as pd

### Importing Dataset
dataset = pd.read_csv('Adult.csv',encoding='utf-8')

# Visualização dos atributos
dataset.info()

In [ ]:
missing = dataset.isnull().sum()
print(missing)

In [ ]:
## Deletando (apagando) todas as linhas com missing values
dataset2 = dataset.dropna()
missing = dataset2.isnull().sum()
print(missing)

In [ ]:
##Suavizando os missing values, ao invés de deletar e sofrer o provável desbalanceamento
##Importando a função para achar a moda
from scipy.stats import mode

##Alterando missing com a moda
dataset['workclass'].fillna(mode(dataset['workclass']).mode[0],inplace=True)
dataset['occupation'].fillna(mode(dataset['occupation']).mode[0], inplace=True)
dataset['native_country'].fillna(mode(dataset['native_country']).mode[0],inplace=True)

dataset.head(10)

In [ ]:
###  NORMALIZANDO ATRIBUTOS NUMÉRICOS ###

## Carregando Library para normalizar atributos numéricos
from sklearn.preprocessing import minmax_scale

# Obtendo os nomes das colunas Numéricas
tipos_numericos = ['int64']
cols_num = dataset.select_dtypes(include=tipos_numericos)

## selecionando as colunas
colunas_numericas = list(cols_num.columns)

# Copiando os dados e aplicando a normalizacao
dados_normalizados = dataset.copy()
dados_normalizados[colunas_numericas] = dataset[colunas_numericas].apply(minmax_scale)

# Visualização dos dados normalizados
dados_normalizados.head(10)

In [ ]:
## BINARIZAÇÃO DE ATRIBUTOS CATEGÓRICOS

## Pegar a classe
col_classe = dataset['class']

## Apagar a classe
dataset.drop('class',inplace=True,axis=1) #??????

#Obtendo os nomes das colunas categóricas
tipos_categoricos = ['object']
cols_cat = dataset.select_dtypes(include=tipos_categoricos)

# Binarizando os atributos categóricos
categoricoToBinary = pd.get_dummies(cols_cat) # pesquisar ?????
dados = dataset.join(categoricoToBinary)

# Dropando os atributos categóricos originais
dados.drop(cols_cat.columns.to_list(),axis=1,inplace=True)

# Juntando o atributo classe
final_data = dados.join(col_classe) # o que é esse class??????

#Visualização dos dados categóricos normalizados
final_data.head()

In [36]:
##DISCRETIZANDO ATRIBUTOS NUMÉRICOS (PROCESSO INVERSO À TRANSFORMAÇÃO NOMINAL->NUMÉRICA)

#Ordena as idades
np.array(sorted(dataset.age.unique()))

# insere o atributo nominal com 3 categorias
dataset['age_nominal'] = pd.cut(dataset.age,bins=3,labels=['jovem','adulto','idoso']) ## Como isso é dividido (numericamente) internamente????

#Visualização dos dados normalizados (discretizados)

dataset.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,age_nominal
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,jovem
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,jovem
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,jovem
3,44,Private,160323,NaN,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,adulto
4,18,Private,103497,Some-college,10,Never-married,Prof-specialty,Own-child,White,Female,0,0,30,United-States,jovem